name: fancy_switch
description: A customizable fancy animated switch with support for icons and SVGs.
version: 0.0.1

homepage: https://github.com/YOUR_GITHUB/fancy_switch
repository: https://github.com/YOUR_GITHUB/fancy_switch
issue_tracker: https://github.com/YOUR_GITHUB/fancy_switch/issues
maintainer: Mohammad Mahdi <YOUR_EMAIL>

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
