name: fancy_switch
description: A beautiful, customizable, animated Flutter switch with support for IconData and SVGs. Perfect for adding smooth, modern toggle buttons to your app.
version: 1.0.0+1
homepage: https://github.com/unclegenson/fancy_switch
repository: https://github.com/unclegenson/fancy_switch.git
issue_tracker: https://github.com/unclegenson/fancy_switch/issues
maintainer: UncleGenSon <unclegenson@gmail.com>

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

publish_to: 'https://pub.dev'